Sk latex behaviour
overleaf/ace pull request #2
Opened 2017-07-05 13:32 UTC by ShaneKilkelly

2017-07-06 11:10 UTC, jpallen requested changes
LGTM, just a few bits of dead code still 👍

2017-07-06 11:10 UTC, jpallen commented on lib/ace/mode/behaviour/latex.js
> +LatexBehaviour.recordMaybeInsert = function(editor, session, bracket) {
This seems to be a dead method now.

2017-07-06 11:10 UTC, jpallen commented on lib/ace/mode/behaviour/latex.js
> +LatexBehaviour.isMaybeInsertedClosing = function(cursor, line) {
Also dead

2017-07-06 11:10 UTC, jpallen commented on lib/ace/mode/behaviour/latex.js
> +LatexBehaviour.clearMaybeInsertedClosing = function() {
Dead

2017-07-06 14:00 UTC, ShaneKilkelly commented
@jpallen dead code removed

2017-08-04 08:35 UTC, jpallen approved these changes

2017-08-04 08:35 UTC, merged